INSERT INTO cxr.nota(VALOR_NOTA, QT_DISPONIVEL) VALUES(100, 10);
INSERT INTO cxr.nota(VALOR_NOTA, QT_DISPONIVEL) VALUES(50, 5);
INSERT INTO cxr.nota(VALOR_NOTA, QT_DISPONIVEL) VALUES(20, 2);
INSERT INTO cxr.nota(VALOR_NOTA, QT_DISPONIVEL) VALUES(10, 8);